import React from "react"
import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import { Inter } from "next/font/google"
import Layout from "@/components/layouts/Layout"
import "./globalStyles/index.scss"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Event App",
  description: "Generated by create next app",
  authors: [{ name: "Vlad", url: "t.me/gapanovichV" }]
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </html>
    </ClerkProvider>
  )
}
